apiVersion: v2
name: demo-game
description: demo-gamge
type: application
version: 999.999.999
appVersion: "999.999.999"

dependencies:
  - name: platform
    version: "1.2.27"
    repository: "oci://docker.registry.cheetah.games"